# Generated by Django 3.0 on 2019-12-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMPARE', '0002_auto_20191219_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
