# Generated by Django 3.0 on 2019-12-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMPARE', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('price', models.IntegerField()),
                ('image_url', models.TextField()),
                ('s_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crawl_inf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'discuss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('c_or_b', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'merchandise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pchome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(blank=True, db_column='product_Id', null=True)),
            ],
            options={
                'db_table': 'pchome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shopee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.TextField(blank=True, null=True)),
                ('itemid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shopee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, null=True, unique=True)),
                ('passward', models.TextField(blank=True, null=True)),
                ('nickname', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yahoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ec_productid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yahoo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Evalution',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
